import { randomBytes, timingSafeEqual } from 'node:crypto';
import { RENAME_PRICE, STARTER_CHAMPIONS } from '@mini-clash/data';
import { argon2id, argon2Verify } from 'hash-wasm';
import type { Sql } from './db';
import { ApiError } from './errors';
import { spend } from './ledger';

/**
 * Identity (TECH §9–§10).
 *
 * **A guest and a registered player are the same row.** Signing up does not
 * create an account, it adds a credential to the one you already had — so the
 * coins, unlocks and mastery earned before you ever typed an email survive by
 * construction rather than by a migration step somebody has to remember to run.
 * The device key stays valid afterwards, so the browser you upgraded from does
 * not get logged out as a reward for signing up.
 */

/** OWASP's argon2id baseline: 19 MiB, 2 passes, 1 lane. */
const ARGON = { parallelism: 1, iterations: 2, memorySize: 19456, hashLength: 32 } as const;

export const SESSION_COOKIE = 'mc_session';
const SESSION_DAYS = 30;
/** Cookie `Max-Age`, in seconds — kept in step with the row's expiry. */
export const SESSION_MAX_AGE = SESSION_DAYS * 24 * 3600;

export interface SessionUser {
  id: string;
  kind: 'guest' | 'registered';
  name: string;
  email: string | null;
}

export interface Session {
  token: string;
  csrf: string;
  user: SessionUser;
}

export class AuthError extends ApiError {}

const id = (prefix: string): string => `${prefix}_${randomBytes(12).toString('hex')}`;
const token = (): string => randomBytes(32).toString('base64url');

async function hash(password: string): Promise<string> {
  return argon2id({ password, salt: randomBytes(16), ...ARGON, outputType: 'encoded' });
}

/** Constant-time compare that tolerates length differences without leaking them. */
function safeEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) {
    // Still burn a comparison so the timing does not advertise the mismatch.
    timingSafeEqual(ab, ab);
    return false;
  }
  return timingSafeEqual(ab, bb);
}

/* -------------------------------- Sessions -------------------------------- */

async function issue(sql: Sql, user: SessionUser): Promise<Session> {
  const t = token();
  const csrf = token();
  const expires = new Date(Date.now() + SESSION_DAYS * 24 * 3600 * 1000);
  await sql`insert into sessions (token, user_id, csrf, expires_at)
            values (${t}, ${user.id}, ${csrf}, ${expires})`;
  return { token: t, csrf, user };
}

export async function sessionFor(sql: Sql, t: string | undefined): Promise<Session | null> {
  if (!t) return null;
  const rows = await sql<{
    token: string;
    csrf: string;
    id: string;
    kind: 'guest' | 'registered';
    name: string;
    email: string | null;
  }>`select s.token, s.csrf, u.id, u.kind, u.name, u.email
       from sessions s join users u on u.id = s.user_id
      where s.token = ${t} and s.expires_at > now()`;
  const r = rows[0];
  if (!r) return null;
  return {
    token: r.token,
    csrf: r.csrf,
    user: { id: r.id, kind: r.kind, name: r.name, email: r.email },
  };
}

export async function logout(sql: Sql, t: string | undefined): Promise<void> {
  if (t) await sql`delete from sessions where token = ${t}`;
}

/** Drop every session but this one — used after a password change. */
export async function revokeOtherSessions(sql: Sql, userId: string, keep: string): Promise<void> {
  await sql`delete from sessions where user_id = ${userId} and token <> ${keep}`;
}

/* --------------------------------- Names ---------------------------------- */

const NAME_RE = /^[\p{L}\p{N} _.'-]{2,16}$/u;

export function validName(name: string): boolean {
  return NAME_RE.test(name.trim());
}

/* ------------------------------- Accounts --------------------------------- */

/**
 * Everything a brand-new account starts with. Written in the same transaction
 * as the user row, so there is no window in which a player exists but owns
 * nothing.
 */
async function seedAccount(sql: Sql, userId: string): Promise<void> {
  await sql`insert into profiles (user_id) values (${userId})`;
  for (const champ of STARTER_CHAMPIONS) {
    await sql`insert into unlocks (user_id, kind, ref_id) values (${userId}, 'champion', ${champ})`;
  }
}

/**
 * Sign in the device, creating the account on first sight.
 *
 * The device key is generated by the browser and kept in local storage; it is a
 * credential, so it is never echoed back and never appears in a URL.
 */
export async function guest(sql: Sql, name: string, deviceKey: string): Promise<Session> {
  if (!validName(name)) throw new AuthError(400, 'bad_name');
  if (deviceKey.length < 16) throw new AuthError(400, 'bad_device_key');
  return sql.begin(async (tx) => {
    const existing = await tx<{
      id: string;
      kind: 'guest' | 'registered';
      name: string;
      email: string | null;
    }>`select id, kind, name, email from users where device_key = ${deviceKey}`;
    if (existing[0]) return issue(tx, existing[0]);

    const userId = id('u');
    await tx`insert into users (id, kind, name, device_key)
             values (${userId}, 'guest', ${name.trim()}, ${deviceKey})`;
    await seedAccount(tx, userId);
    return issue(tx, { id: userId, kind: 'guest', name: name.trim(), email: null });
  });
}

/**
 * Attach an email + password to the account you are already playing.
 *
 * Deliberately an UPDATE, never an INSERT: this is the single line that makes
 * "play now, sign up later" not cost you your progress.
 */
export async function upgrade(
  sql: Sql,
  userId: string,
  email: string,
  password: string,
): Promise<void> {
  const clean = email.trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(clean)) throw new AuthError(400, 'bad_email');
  if (password.length < 8) throw new AuthError(400, 'weak_password');
  const pw = await hash(password);
  await sql.begin(async (tx) => {
    const rows = await tx<{ kind: string }>`select kind from users where id = ${userId} for update`;
    if (!rows[0]) throw new AuthError(404, 'no_user');
    if (rows[0].kind === 'registered') throw new AuthError(409, 'already_registered');
    const taken = await tx<{ id: string }>`select id from users where email = ${clean}`;
    if (taken[0]) throw new AuthError(409, 'email_taken');
    await tx`update users set kind = 'registered', email = ${clean}, password_hash = ${pw}
             where id = ${userId}`;
  });
}

export async function login(sql: Sql, email: string, password: string): Promise<Session> {
  const clean = email.trim().toLowerCase();
  const rows = await sql<{
    id: string;
    kind: 'guest' | 'registered';
    name: string;
    email: string | null;
    password_hash: string | null;
  }>`select id, kind, name, email, password_hash from users where email = ${clean}`;
  const u = rows[0];
  // Same error and a real verification either way: whether an email is
  // registered is not something an unauthenticated caller gets to learn.
  const stored =
    u?.password_hash ??
    '$argon2id$v=19$m=19456,t=2,p=1$AAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
  let ok = false;
  try {
    ok = await argon2Verify({ password, hash: stored });
  } catch {
    ok = false;
  }
  if (!u || !ok) throw new AuthError(401, 'bad_credentials');
  return issue(sql, { id: u.id, kind: u.kind, name: u.name, email: u.email });
}

/**
 * Rename (UI_UX §13 account panel: one free change, then it costs).
 *
 * The counter and the charge move in the same transaction as the name, so a
 * crash between them cannot hand out a second free change — or take the coins
 * for one that never happened.
 */
export async function rename(sql: Sql, userId: string, name: string): Promise<RenameResult> {
  const clean = name.trim();
  if (!validName(clean)) throw new AuthError(400, 'bad_name');
  return sql.begin(async (tx) => {
    const rows = await tx<{ name_changes: number }>`
      select name_changes from profiles where user_id = ${userId} for update`;
    if (!rows[0]) throw new AuthError(404, 'no_user');
    const used = rows[0].name_changes;
    const charged = used > 0 ? RENAME_PRICE : 0;
    if (charged > 0) await spend(tx, userId, charged, 'rename');
    await tx`update users set name = ${clean} where id = ${userId}`;
    await tx`update profiles set name_changes = name_changes + 1 where user_id = ${userId}`;
    return { name: clean, charged, freeChangeLeft: false };
  });
}

export interface RenameResult {
  name: string;
  /** Coins actually taken — 0 for the one free change. */
  charged: number;
  freeChangeLeft: boolean;
}

/** What a rename would cost right now, for the confirm dialog. */
export async function renameQuote(sql: Sql, userId: string): Promise<number> {
  const rows = await sql<{ name_changes: number }>`
    select name_changes from profiles where user_id = ${userId}`;
  return (rows[0]?.name_changes ?? 0) > 0 ? RENAME_PRICE : 0;
}

/** Delete the account and everything hanging off it (cascades do the work). */
export async function deleteAccount(sql: Sql, userId: string): Promise<void> {
  await sql`delete from users where id = ${userId}`;
}

/* ---------------------------------- CSRF ---------------------------------- */

/**
 * Cookies ride along automatically, so a mutating route needs proof the caller
 * meant it. The token is handed out with the session and echoed in a header.
 */
export function checkCsrf(session: Session, header: string | undefined): void {
  if (!header || !safeEqual(session.csrf, header)) throw new AuthError(403, 'bad_csrf');
}
